### ISSUE TITLE
Babel

### ISSUE THREAD

**Issue by gingur** [godaddy/breakdancer#3]
This repository does not expose the library as a module to be used as a link in a browser, nor does it convert the source to ES5 compatible code to be use as a library via node_modules.  The only way this repository could be used then is if the consumer provided such logic.

**Comment by indexzero** [comment]
That is correct. Your contributions to change this are welcome.

**Comment by gingur** [comment]
I don't consider this a feature, this is a bug.  Your library is not ready to be released until such functionality is added.

**Comment by indexzero** [comment]
Well yes and no. Depends on how you look at it. Right now we're consuming this via pure ES6 in a high-level projects webpack-based build and it works just fine. That being said we could definitely do better on communicating how to consume it and/or providing multiple ways to do so as you've suggested.

**Comment by gingur** [comment]
Yes, adding the required webpack/babel configuration would maybe clear up the intention that this will not be converted before publishing.  One thing to note is that babel-loader should be excluding `node_modules` from being executed, because this single library does require it to be executed via babel-loader the suggested excluded should contain the `require.resolve` path to the module.

**Comment by gingur** [comment]
Here is an example solution to use this library without the appropriate build step, http://stackoverflow.com/a/31822668

**Comment by gingur** [comment]
PR https://github.com/godaddy/breakdancer/pull/4
