### ISSUE TITLE
Can we add the support of React Native on breakdancer?

### ISSUE THREAD

**Issue by yhan64** [godaddy/breakdancer#8]
React Native provides a `Dimension.get()` function to get viewports of a native app: https://facebook.github.io/react-native/docs/dimensions.html#get
Can we add RN support on breakdancer using that function?

**Comment by yhan64** [comment]
https://github.com/yhan64/breakdancer/blob/master/index.native.js
Above approach would work but there would be a lot duplicated codes. Should I separate them into a shared file?

**Comment by indexzero** [comment]
Ohai @yhan64! I am definitely +1 on adding `react-native` support ... could you make a PR with your changes and we'll discuss there?

**Comment by yhan64** [comment]
https://github.com/godaddy/breakdancer/pull/9
created :)

**Comment by 3rd-Eden** [comment]
Closing as this has been addressed in the latest release.
